default_text_model: "bge_small_en_v1.5_text"
default_multimodal_model: "clip_vit_b_32_multimodal"

ragoon_models:
  - name: "bge_small_en_v1.5_text"
    model_path: "BAAI/bge-small-en-v1.5"
    type: "text"
    params:
      query_prefix: "Represent this sentence for searching relevant passages: "

  - name: "clip_vit_b_32_multimodal"
    model_path: "openai/clip-vit-base-patch32"
    type: "multimodal"
    params: {}
